#!/usr/bin/env bash
# ~/.bash_aliases

# update & upgrade & autoremove
alias uua='sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y'

# audio restart (from Ubuntu podcast)
alias restart-audio='systemctl --user restart pulseaudio'
# bad way to restart
# pulseaudio -k && sudo alsa force-reload

# some more aliases
alias ..='cd ..'
alias l='ls -CF'
# alias l='ls -l'
alias ll='ls -AlF'
alias la='ls -A'
# alias la='ls -Al'
alias lss='ls -lAsh'
alias tree='tree -C'
alias trls='tree -C | less -R'	# -C outputs colour, -R makes less understand color
alias mode='(set -o | grep emacs.*on >/dev/null 2>&1 && echo "emacs mode" || echo "vi mode")'

# git
# Ignore changes to already tracked files
alias untrack='git update-index --assume-unchanged'
alias retrack='git update-index --no-assume-unchanged'

# Like rm, but safer since it uses trash-cli
alias tp=trash-put

# Find big files/directories
alias space-left=baobab

# Copy with progress bar
alias cpv='rsync -ah --info=progress2'

# Colored grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# "pi ip" Find my pi's IP address
alias piip='arp -na | grep -i b8:27:eb'

# For the XPS13
alias cctk=/opt/dell/dcc/cctk

alias audio-laptop='pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo'
# https://unix.stackexchange.com/questions/62818/how-can-i-switch-between-different-audio-output-hardware-using-the-shell
# alias audio-hdmi='pacmd set-card-profile 0 output:hdmi-stereo+input:analog-stereo'
# xrandr --output <other screen> --same-as <main screen>


# For typos
alias neovim='nvim'
